services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: >
      sh -c "
        python manage.py migrate &&
        gunicorn backend.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
